# Generated by Django 4.2 on 2023-11-17 19:00

import controlfreakapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easting', models.DecimalField(decimal_places=8, max_digits=20)),
                ('northing', models.DecimalField(decimal_places=8, max_digits=20)),
                ('elevation', models.DecimalField(decimal_places=8, max_digits=20)),
                ('flavour', models.CharField(blank=True, choices=[('AD', 'Adjusted'), ('ME', 'Averaged'), ('RW', 'Raw'), ('HM', 'Helmert'), ('OP', 'Over Point'), ('BS', 'Backsite')], max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HelmertResection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helmert_id', models.CharField(max_length=15)),
                ('setup_type', models.CharField(blank=True, max_length=50, null=True)),
                ('origin_elevation', models.DecimalField(decimal_places=3, max_digits=20)),
                ('instrument_height', models.DecimalField(decimal_places=3, max_digits=20)),
                ('bearing_swing', models.DecimalField(decimal_places=3, max_digits=20)),
                ('utc_time', models.DateTimeField()),
                ('pos_error', models.DecimalField(decimal_places=3, max_digits=20)),
                ('scale_factor', models.DecimalField(decimal_places=5, max_digits=6)),
                ('level_diff', models.DecimalField(decimal_places=3, max_digits=20)),
                ('coordinates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='helmert_resections', to='controlfreakapp.coordinates')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentMeasureStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_measure_style_id', models.IntegerField(blank=True, null=True)),
                ('instrument_measure_style_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_settings_id', models.IntegerField(blank=True, null=True)),
                ('instrument_settings_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OverPointStationSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ops_id', models.CharField(max_length=15)),
                ('setup_type', models.CharField(blank=True, max_length=50, null=True)),
                ('origin_elevation', models.DecimalField(decimal_places=3, max_digits=20)),
                ('instrument_height', models.DecimalField(decimal_places=3, max_digits=20)),
                ('bearing_swing', models.DecimalField(decimal_places=3, max_digits=20)),
                ('utc_time', models.DateTimeField()),
                ('bs_id', models.CharField(max_length=15)),
                ('bs_calc_elevation', models.DecimalField(decimal_places=3, max_digits=20)),
                ('bs_elevation_delta', models.DecimalField(decimal_places=3, max_digits=20)),
                ('bs_easting_delta', models.DecimalField(decimal_places=3, max_digits=20)),
                ('bs_northing_delta', models.DecimalField(decimal_places=3, max_digits=20)),
                ('bs_diff_z', models.DecimalField(decimal_places=3, max_digits=20)),
                ('bs_coordinates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_station_setups_bs', to='controlfreakapp.coordinates')),
                ('coordinates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_station_setups', to='controlfreakapp.coordinates')),
            ],
        ),
        migrations.CreateModel(
            name='ReflectorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reflector_type_id', models.IntegerField(blank=True, null=True)),
                ('reflector_type_name', models.CharField(blank=True, max_length=50, null=True)),
                ('reflector_constant', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TertiaryControlFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=controlfreakapp.models.get_tertiary_upload_path)),
                ('revision', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_hash', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('observation_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnAdjustedTertiaryControlPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(blank=True, max_length=15, null=True)),
                ('target_type', models.CharField(blank=True, max_length=15, null=True)),
                ('horizontal_quality', models.IntegerField()),
                ('vertical_quality', models.IntegerField()),
                ('adjusted', models.BooleanField()),
                ('coordinates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='un_adjusted_control_points', to='controlfreakapp.coordinates')),
                ('otp_setup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='controlfreakapp.overpointstationsetup')),
                ('resection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='controlfreakapp.helmertresection')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlfreakapp.tertiarycontrolfile')),
            ],
        ),
        migrations.CreateModel(
            name='ResectionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helm_id', models.CharField(max_length=15)),
                ('model_name', models.CharField(blank=True, max_length=50, null=True)),
                ('target_type', models.CharField(blank=True, max_length=50, null=True)),
                ('use_pos', models.BooleanField()),
                ('use_ht', models.BooleanField()),
                ('pos_error', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('coordinates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resection_points', to='controlfreakapp.coordinates')),
                ('resection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlfreakapp.helmertresection')),
                ('tps_measure_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='controlfreakapp.instrumentmeasurestyle')),
                ('tps_reflector_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='controlfreakapp.reflectortype')),
                ('tps_settings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='controlfreakapp.instrumentsettings')),
            ],
        ),
        migrations.AddField(
            model_name='helmertresection',
            name='source_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='helmert_resections', to='controlfreakapp.tertiarycontrolfile'),
        ),
        migrations.AddConstraint(
            model_name='unadjustedtertiarycontrolpoint',
            constraint=models.UniqueConstraint(fields=('resection', 'coordinates'), name='resection_coordinates'),
        ),
        migrations.AddConstraint(
            model_name='overpointstationsetup',
            constraint=models.UniqueConstraint(fields=('ops_id', 'coordinates', 'bs_coordinates'), name='ops_id_coordinates'),
        ),
        migrations.AddConstraint(
            model_name='helmertresection',
            constraint=models.UniqueConstraint(fields=('helmert_id', 'coordinates'), name='helmert_id_coordinates'),
        ),
    ]
