# Generated by Django 4.2 on 2023-11-17 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlfreakapp', '0002_alter_tertiarycontrolfile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AveragedTertiaryControlPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(blank=True, max_length=15, null=True)),
                ('target_type', models.CharField(blank=True, max_length=15, null=True)),
                ('horizontal_quality', models.IntegerField()),
                ('vertical_quality', models.IntegerField()),
                ('a_seed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_seed', to='controlfreakapp.unadjustedtertiarycontrolpoint')),
                ('b_seed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b_seed', to='controlfreakapp.unadjustedtertiarycontrolpoint')),
                ('coordinates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='averaged_control_points', to='controlfreakapp.coordinates')),
            ],
        ),
        migrations.AddConstraint(
            model_name='averagedtertiarycontrolpoint',
            constraint=models.UniqueConstraint(fields=('a_seed', 'b_seed', 'coordinates'), name='a_seed_b_seed_coordinates'),
        ),
    ]
